name: 03-Node Js Setup

on:
  push:
    branches: ["*"]

jobs:
    node-setup:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
            - uses: actions/setup-node@v7
              with:
                node-version: '22'
            - run: npm install
            - run: node index.js