name: Mappings and dependency

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'select environment for deployment'
        required: true
        type: choice
        options:
            - dev
            - uat
            - prod
jobs:
    code:
        runs-on: ubuntu-latest
        steps:
            - name: Clone the repo
              run: echo "Code cloned here" 

    build:
        needs: [code]
        runs-on: ubuntu-latest
        steps:
            - name: build the code
              run: echo "Code build here"

    test:
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            - name: Code test here
              run: echo "Code tests here"

    deploy-to-dev:
        needs: [build, test]
        if: ${{ inputs.environment == 'dev'}}
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to Dev
              run: echo "Code deploy to Dev"

    deploy-to-uat:
        needs: [build, test]
        if: ${{ inputs.environment == 'uat'}}
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to uat
              run: echo "Code deploy to uat"