name: dependency scan with pip-audit

on:
    workflow_dispatch:

jobs: 
    validate:
        runs-on: ubuntu-latest
        
        strategy:
            fail-fast: false
            matrix:
                python-version: [3.12]
        
        steps:
            - name: checkout the code
              uses: actions/checkout@v7

            - name: setup python 3.12
              uses: actions/setup-python@v7
              with:
                python-version: '3.12'

            - name: Install pip-audit
              run: pip install pip-audit

            - name: Audit Dependencies for CVE
              run: pip-audit -r requirements.txt