name: Conditional Workflow

on:
    push:
        branches: ["*"]

jobs:
  run-always:
    runs-on: ubuntu-24.04
    steps:
        - name: Print my name
          run: echo "This job is running always"

  only-on-main:
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/main'
    steps:
        - name: Print my name
          run: echo "This job is running only on main branch"
            


