name: MyFirst Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '32 14 * * 3'
  
jobs:
   Myfirstjob:
    runs-on: ubuntu-24.04
    steps:
    - name: Print my name
      run: echo "hello, Am Vinod and Am learning GHA"





