name: Rename Existing S3 Bucket

on:
  workflow_dispatch:
    inputs:
      old_bucket_name:
        description: 'Existing bucket name'
        required: true
        type: string
      new_bucket_name:
        description: 'New bucket name'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  rename-bucket:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::826496718087:role/s3-gha-access-role
          aws-region: ap-south-1

      - name: Create new bucket
        run: aws s3api create-bucket --bucket s3://${{ github.event.inputs.new_bucket_name }} --region ap-south-1 --create-bucket-configuration LocationConstraint=ap-south-1

      - name: Copy objects
        run: aws s3 sync s3://${{ github.event.inputs.old_bucket_name }} s3://${{ github.event.inputs.new_bucket_name }}

      - name: Delete old bucket
        run: |
          aws s3 rm s3://${{ github.event.inputs.old_bucket_name }}
          aws s3api delete-bucket --bucket s3://${{ github.event.inputs.old_bucket_name }} --region ap-south-1
          aws s3 ls