name: Rename Existing S3 Bucket

on:
  workflow_dispatch:
    inputs:
      old_bucket_name:
        description: 'Existing bucket name'
        required: true
        type: string
      new_bucket_name:
        description: 'New bucket name'
        required: true
        type: string

jobs:
  rename-bucket:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create new bucket
        run: |
          aws s3api create-bucket \
            --bucket ${{ github.event.inputs.new_bucket_name }} \
            --region ap-south-1 \
            --create-bucket-configuration LocationConstraint=ap-south-1

      - name: Copy objects to new bucket
        run: |
          aws s3 sync s3://${{ github.event.inputs.old_bucket_name }} s3://${{ github.event.inputs.new_bucket_name }}

      - name: Delete old bucket
        run: |
          aws s3 rm s3://${{ github.event.inputs.old_bucket_name }} --recursive
          aws s3 api delete-bucket --bucket ${{ github.event.inputs.old_bucket_name }} --region ap-south-1
          aws s3 ls